name:                semux-delegate-alerts
version:             0.1.0.0
github:              "witoldsz/semux-delegate-alerts"
license:             BSD3
author:              "Witold Szczerba"
maintainer:          "witoldsz.dev@gmail.com"
copyright:           "2019 Witold Szczerba"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            semux blockchain

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/semux-discord#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- text
- aeson
- bytestring
- http-conduit
- time
library:
  source-dirs: src

executables:
  semux-delegate-alerts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semux-delegate-alerts

tests:
  semux-delegate-alerts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semux-delegate-alerts
default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude